services:
  mysql:
    image: mysql:8.0
    container_name: seedai-mysql-1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ai_dataset
    volumes:
      - ./mysql_data/data:/var/lib/mysql
      - ./mysql_data/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: seedai-backend-1
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./data/uploads:/app/uploads
      - ./data/datasets:/app/datasets
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpass
      - DB_NAME=ai_dataset
      - MODEL_PATH=/app/pytorch_model/weights/yolov5s.pt
    depends_on:
      - mysql
    restart: unless-stopped

  ai_worker:
    build:
      context: ./pytorch_model
      dockerfile: Dockerfile
    container_name: seedai-ai_worker-1
    volumes:
      - ./pytorch_model:/workspace
    
    depends_on:
      - backend
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./tests:/usr/share/nginx/html/tests
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: unless-stopped